# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Test_0410.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

import mplwidget
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1189, 776)
        MainWindow.setMinimumSize(QtCore.QSize(1175, 622))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(191, 191, 191))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.stackedWidget_List = QtGui.QStackedWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget_List.sizePolicy().hasHeightForWidth())
        self.stackedWidget_List.setSizePolicy(sizePolicy)
        self.stackedWidget_List.setMinimumSize(QtCore.QSize(265, 0))
        self.stackedWidget_List.setObjectName(_fromUtf8("stackedWidget_List"))
        self.Listpage_Agilent = QtGui.QWidget()
        self.Listpage_Agilent.setObjectName(_fromUtf8("Listpage_Agilent"))
        self.verticalLayout = QtGui.QVBoxLayout(self.Listpage_Agilent)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.toolBox_AG = QtGui.QToolBox(self.Listpage_Agilent)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_AG.sizePolicy().hasHeightForWidth())
        self.toolBox_AG.setSizePolicy(sizePolicy)
        self.toolBox_AG.setMinimumSize(QtCore.QSize(250, 451))
        self.toolBox_AG.setMaximumSize(QtCore.QSize(250, 16777215))
        self.toolBox_AG.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolBox_AG.setFont(font)
        self.toolBox_AG.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBox_AG.setAutoFillBackground(False)
        self.toolBox_AG.setStyleSheet(_fromUtf8("QToolBox{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
""))
        self.toolBox_AG.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox_AG.setLineWidth(1)
        self.toolBox_AG.setObjectName(_fromUtf8("toolBox_AG"))
        self.boxpageTable_AG = QtGui.QWidget()
        self.boxpageTable_AG.setGeometry(QtCore.QRect(0, 0, 250, 523))
        self.boxpageTable_AG.setObjectName(_fromUtf8("boxpageTable_AG"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.boxpageTable_AG)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.boxTableLabel_AG = QtGui.QLabel(self.boxpageTable_AG)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boxTableLabel_AG.setFont(font)
        self.boxTableLabel_AG.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.boxTableLabel_AG.setAutoFillBackground(False)
        self.boxTableLabel_AG.setText(_fromUtf8(""))
        self.boxTableLabel_AG.setIndent(-1)
        self.boxTableLabel_AG.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.boxTableLabel_AG.setObjectName(_fromUtf8("boxTableLabel_AG"))
        self.verticalLayout_20.addWidget(self.boxTableLabel_AG)
        self.boxTableBtnCalc_AG = QtGui.QPushButton(self.boxpageTable_AG)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxTableBtnCalc_AG.setFont(font)
        self.boxTableBtnCalc_AG.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.boxTableBtnCalc_AG.setObjectName(_fromUtf8("boxTableBtnCalc_AG"))
        self.verticalLayout_20.addWidget(self.boxTableBtnCalc_AG)
        spacerItem = QtGui.QSpacerItem(140, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_20.addItem(spacerItem)
        self.boxTableListWidget_AG = QtGui.QListWidget(self.boxpageTable_AG)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxTableListWidget_AG.sizePolicy().hasHeightForWidth())
        self.boxTableListWidget_AG.setSizePolicy(sizePolicy)
        self.boxTableListWidget_AG.setObjectName(_fromUtf8("boxTableListWidget_AG"))
        self.verticalLayout_20.addWidget(self.boxTableListWidget_AG)
        self.toolBox_AG.addItem(self.boxpageTable_AG, _fromUtf8(""))
        self.boxpageDiagram_AG = QtGui.QWidget()
        self.boxpageDiagram_AG.setGeometry(QtCore.QRect(0, 0, 250, 523))
        self.boxpageDiagram_AG.setObjectName(_fromUtf8("boxpageDiagram_AG"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.boxpageDiagram_AG)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.boxDiagramBtnPlot_AG = QtGui.QPushButton(self.boxpageDiagram_AG)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxDiagramBtnPlot_AG.setFont(font)
        self.boxDiagramBtnPlot_AG.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.boxDiagramBtnPlot_AG.setObjectName(_fromUtf8("boxDiagramBtnPlot_AG"))
        self.verticalLayout_21.addWidget(self.boxDiagramBtnPlot_AG)
        self.boxDiagramBtnNW_AG = QtGui.QPushButton(self.boxpageDiagram_AG)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.boxDiagramBtnNW_AG.setFont(font)
        self.boxDiagramBtnNW_AG.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.boxDiagramBtnNW_AG.setObjectName(_fromUtf8("boxDiagramBtnNW_AG"))
        self.verticalLayout_21.addWidget(self.boxDiagramBtnNW_AG)
        self.boxDiagramListWidget_AG = QtGui.QListWidget(self.boxpageDiagram_AG)
        self.boxDiagramListWidget_AG.setAlternatingRowColors(False)
        self.boxDiagramListWidget_AG.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.boxDiagramListWidget_AG.setObjectName(_fromUtf8("boxDiagramListWidget_AG"))
        self.verticalLayout_21.addWidget(self.boxDiagramListWidget_AG)
        self.toolBox_AG.addItem(self.boxpageDiagram_AG, _fromUtf8(""))
        self.verticalLayout.addWidget(self.toolBox_AG)
        self.stackedWidget_List.addWidget(self.Listpage_Agilent)
        self.Listpage_Strom = QtGui.QWidget()
        self.Listpage_Strom.setObjectName(_fromUtf8("Listpage_Strom"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.Listpage_Strom)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.toolBox_Strom = QtGui.QToolBox(self.Listpage_Strom)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_Strom.sizePolicy().hasHeightForWidth())
        self.toolBox_Strom.setSizePolicy(sizePolicy)
        self.toolBox_Strom.setMinimumSize(QtCore.QSize(250, 451))
        self.toolBox_Strom.setMaximumSize(QtCore.QSize(250, 16777215))
        self.toolBox_Strom.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolBox_Strom.setFont(font)
        self.toolBox_Strom.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBox_Strom.setAutoFillBackground(False)
        self.toolBox_Strom.setStyleSheet(_fromUtf8("QToolBox{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
""))
        self.toolBox_Strom.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox_Strom.setLineWidth(1)
        self.toolBox_Strom.setObjectName(_fromUtf8("toolBox_Strom"))
        self.boxpageTable_Strom = QtGui.QWidget()
        self.boxpageTable_Strom.setGeometry(QtCore.QRect(0, 0, 250, 523))
        self.boxpageTable_Strom.setObjectName(_fromUtf8("boxpageTable_Strom"))
        self.verticalLayout_22 = QtGui.QVBoxLayout(self.boxpageTable_Strom)
        self.verticalLayout_22.setObjectName(_fromUtf8("verticalLayout_22"))
        self.boxTableLabel_Strom = QtGui.QLabel(self.boxpageTable_Strom)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boxTableLabel_Strom.setFont(font)
        self.boxTableLabel_Strom.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.boxTableLabel_Strom.setAutoFillBackground(False)
        self.boxTableLabel_Strom.setText(_fromUtf8(""))
        self.boxTableLabel_Strom.setIndent(-1)
        self.boxTableLabel_Strom.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.boxTableLabel_Strom.setObjectName(_fromUtf8("boxTableLabel_Strom"))
        self.verticalLayout_22.addWidget(self.boxTableLabel_Strom)
        self.boxTableBtnCalc_Strom = QtGui.QPushButton(self.boxpageTable_Strom)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxTableBtnCalc_Strom.setFont(font)
        self.boxTableBtnCalc_Strom.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.boxTableBtnCalc_Strom.setObjectName(_fromUtf8("boxTableBtnCalc_Strom"))
        self.verticalLayout_22.addWidget(self.boxTableBtnCalc_Strom)
        spacerItem1 = QtGui.QSpacerItem(140, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_22.addItem(spacerItem1)
        self.boxTableListWidget_Strom = QtGui.QListWidget(self.boxpageTable_Strom)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxTableListWidget_Strom.sizePolicy().hasHeightForWidth())
        self.boxTableListWidget_Strom.setSizePolicy(sizePolicy)
        self.boxTableListWidget_Strom.setObjectName(_fromUtf8("boxTableListWidget_Strom"))
        self.verticalLayout_22.addWidget(self.boxTableListWidget_Strom)
        self.toolBox_Strom.addItem(self.boxpageTable_Strom, _fromUtf8(""))
        self.boxpageDiagram_Strom = QtGui.QWidget()
        self.boxpageDiagram_Strom.setGeometry(QtCore.QRect(0, 0, 250, 523))
        self.boxpageDiagram_Strom.setObjectName(_fromUtf8("boxpageDiagram_Strom"))
        self.verticalLayout_23 = QtGui.QVBoxLayout(self.boxpageDiagram_Strom)
        self.verticalLayout_23.setObjectName(_fromUtf8("verticalLayout_23"))
        self.boxDiagramBtnPlot_Strom = QtGui.QPushButton(self.boxpageDiagram_Strom)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxDiagramBtnPlot_Strom.setFont(font)
        self.boxDiagramBtnPlot_Strom.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.boxDiagramBtnPlot_Strom.setObjectName(_fromUtf8("boxDiagramBtnPlot_Strom"))
        self.verticalLayout_23.addWidget(self.boxDiagramBtnPlot_Strom)
        self.boxDiagramBtnNW_Strom = QtGui.QPushButton(self.boxpageDiagram_Strom)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.boxDiagramBtnNW_Strom.setFont(font)
        self.boxDiagramBtnNW_Strom.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.boxDiagramBtnNW_Strom.setObjectName(_fromUtf8("boxDiagramBtnNW_Strom"))
        self.verticalLayout_23.addWidget(self.boxDiagramBtnNW_Strom)
        self.boxDiagramListWidget_Strom = QtGui.QListWidget(self.boxpageDiagram_Strom)
        self.boxDiagramListWidget_Strom.setAlternatingRowColors(False)
        self.boxDiagramListWidget_Strom.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.boxDiagramListWidget_Strom.setObjectName(_fromUtf8("boxDiagramListWidget_Strom"))
        self.verticalLayout_23.addWidget(self.boxDiagramListWidget_Strom)
        self.toolBox_Strom.addItem(self.boxpageDiagram_Strom, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.toolBox_Strom)
        self.stackedWidget_List.addWidget(self.Listpage_Strom)
        self.Listpage_Wetter = QtGui.QWidget()
        self.Listpage_Wetter.setObjectName(_fromUtf8("Listpage_Wetter"))
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.Listpage_Wetter)
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.toolBox_Wetter = QtGui.QToolBox(self.Listpage_Wetter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_Wetter.sizePolicy().hasHeightForWidth())
        self.toolBox_Wetter.setSizePolicy(sizePolicy)
        self.toolBox_Wetter.setMinimumSize(QtCore.QSize(250, 451))
        self.toolBox_Wetter.setMaximumSize(QtCore.QSize(250, 16777215))
        self.toolBox_Wetter.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolBox_Wetter.setFont(font)
        self.toolBox_Wetter.setFocusPolicy(QtCore.Qt.NoFocus)
        self.toolBox_Wetter.setAutoFillBackground(False)
        self.toolBox_Wetter.setStyleSheet(_fromUtf8("QToolBox{\n"
"background-color: rgb(218, 218, 218);\n"
"}\n"
""))
        self.toolBox_Wetter.setFrameShape(QtGui.QFrame.NoFrame)
        self.toolBox_Wetter.setLineWidth(1)
        self.toolBox_Wetter.setObjectName(_fromUtf8("toolBox_Wetter"))
        self.boxpageTable_Wetter = QtGui.QWidget()
        self.boxpageTable_Wetter.setGeometry(QtCore.QRect(0, 0, 250, 523))
        self.boxpageTable_Wetter.setObjectName(_fromUtf8("boxpageTable_Wetter"))
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.boxpageTable_Wetter)
        self.verticalLayout_24.setObjectName(_fromUtf8("verticalLayout_24"))
        self.boxTableLabel_Wetter = QtGui.QLabel(self.boxpageTable_Wetter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.boxTableLabel_Wetter.setFont(font)
        self.boxTableLabel_Wetter.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.boxTableLabel_Wetter.setAutoFillBackground(False)
        self.boxTableLabel_Wetter.setText(_fromUtf8(""))
        self.boxTableLabel_Wetter.setIndent(-1)
        self.boxTableLabel_Wetter.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.boxTableLabel_Wetter.setObjectName(_fromUtf8("boxTableLabel_Wetter"))
        self.verticalLayout_24.addWidget(self.boxTableLabel_Wetter)
        self.boxTableBtnCalc_Wetter = QtGui.QPushButton(self.boxpageTable_Wetter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxTableBtnCalc_Wetter.setFont(font)
        self.boxTableBtnCalc_Wetter.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.boxTableBtnCalc_Wetter.setObjectName(_fromUtf8("boxTableBtnCalc_Wetter"))
        self.verticalLayout_24.addWidget(self.boxTableBtnCalc_Wetter)
        spacerItem2 = QtGui.QSpacerItem(140, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.verticalLayout_24.addItem(spacerItem2)
        self.boxTableListWidget_Wetter = QtGui.QListWidget(self.boxpageTable_Wetter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boxTableListWidget_Wetter.sizePolicy().hasHeightForWidth())
        self.boxTableListWidget_Wetter.setSizePolicy(sizePolicy)
        self.boxTableListWidget_Wetter.setObjectName(_fromUtf8("boxTableListWidget_Wetter"))
        self.verticalLayout_24.addWidget(self.boxTableListWidget_Wetter)
        self.toolBox_Wetter.addItem(self.boxpageTable_Wetter, _fromUtf8(""))
        self.boxpageDiagram_Wetter = QtGui.QWidget()
        self.boxpageDiagram_Wetter.setGeometry(QtCore.QRect(0, 0, 250, 523))
        self.boxpageDiagram_Wetter.setObjectName(_fromUtf8("boxpageDiagram_Wetter"))
        self.verticalLayout_25 = QtGui.QVBoxLayout(self.boxpageDiagram_Wetter)
        self.verticalLayout_25.setObjectName(_fromUtf8("verticalLayout_25"))
        self.boxDiagramBtnPlot_Wetter = QtGui.QPushButton(self.boxpageDiagram_Wetter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.boxDiagramBtnPlot_Wetter.setFont(font)
        self.boxDiagramBtnPlot_Wetter.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.boxDiagramBtnPlot_Wetter.setObjectName(_fromUtf8("boxDiagramBtnPlot_Wetter"))
        self.verticalLayout_25.addWidget(self.boxDiagramBtnPlot_Wetter)
        self.boxDiagramBtnNW_Wetter = QtGui.QPushButton(self.boxpageDiagram_Wetter)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        self.boxDiagramBtnNW_Wetter.setFont(font)
        self.boxDiagramBtnNW_Wetter.setStyleSheet(_fromUtf8("background-color: rgb(240, 240, 240);"))
        self.boxDiagramBtnNW_Wetter.setObjectName(_fromUtf8("boxDiagramBtnNW_Wetter"))
        self.verticalLayout_25.addWidget(self.boxDiagramBtnNW_Wetter)
        self.boxDiagramListWidget_Wetter = QtGui.QListWidget(self.boxpageDiagram_Wetter)
        self.boxDiagramListWidget_Wetter.setAlternatingRowColors(False)
        self.boxDiagramListWidget_Wetter.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.boxDiagramListWidget_Wetter.setObjectName(_fromUtf8("boxDiagramListWidget_Wetter"))
        self.verticalLayout_25.addWidget(self.boxDiagramListWidget_Wetter)
        self.toolBox_Wetter.addItem(self.boxpageDiagram_Wetter, _fromUtf8(""))
        self.verticalLayout_18.addWidget(self.toolBox_Wetter)
        self.stackedWidget_List.addWidget(self.Listpage_Wetter)
        self.gridLayout_6.addWidget(self.stackedWidget_List, 1, 0, 2, 1)
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(250, 60))
        self.listWidget.setMaximumSize(QtCore.QSize(250, 70))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout_6.addWidget(self.listWidget, 0, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setEnabled(True)
        self.stackedWidget.setMinimumSize(QtCore.QSize(761, 400))
        self.stackedWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.stacked_Agilent = QtGui.QWidget()
        self.stacked_Agilent.setObjectName(_fromUtf8("stacked_Agilent"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.stacked_Agilent)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.tabWidget_Agilent = QtGui.QTabWidget(self.stacked_Agilent)
        self.tabWidget_Agilent.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Agilent.sizePolicy().hasHeightForWidth())
        self.tabWidget_Agilent.setSizePolicy(sizePolicy)
        self.tabWidget_Agilent.setMinimumSize(QtCore.QSize(691, 400))
        self.tabWidget_Agilent.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_Agilent.setSizeIncrement(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget_Agilent.setFont(font)
        self.tabWidget_Agilent.setMouseTracking(False)
        self.tabWidget_Agilent.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget_Agilent.setAcceptDrops(False)
        self.tabWidget_Agilent.setAutoFillBackground(False)
        self.tabWidget_Agilent.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_Agilent.setDocumentMode(True)
        self.tabWidget_Agilent.setTabsClosable(False)
        self.tabWidget_Agilent.setMovable(True)
        self.tabWidget_Agilent.setObjectName(_fromUtf8("tabWidget_Agilent"))
        self.AG_tab2table = QtGui.QWidget()
        self.AG_tab2table.setObjectName(_fromUtf8("AG_tab2table"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.AG_tab2table)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.AG_tab2TableView = QtGui.QTableView(self.AG_tab2table)
        self.AG_tab2TableView.setMinimumSize(QtCore.QSize(631, 300))
        self.AG_tab2TableView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.AG_tab2TableView.setAutoFillBackground(True)
        self.AG_tab2TableView.setShowGrid(True)
        self.AG_tab2TableView.setObjectName(_fromUtf8("AG_tab2TableView"))
        self.verticalLayout_3.addWidget(self.AG_tab2TableView)
        self.tabWidget_Agilent.addTab(self.AG_tab2table, _fromUtf8(""))
        self.AG_tab2Calc = QtGui.QWidget()
        self.AG_tab2Calc.setObjectName(_fromUtf8("AG_tab2Calc"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.AG_tab2Calc)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.AG_tab2CalcTab = QtGui.QTableView(self.AG_tab2Calc)
        self.AG_tab2CalcTab.setObjectName(_fromUtf8("AG_tab2CalcTab"))
        self.verticalLayout_13.addWidget(self.AG_tab2CalcTab)
        self.tabWidget_Agilent.addTab(self.AG_tab2Calc, _fromUtf8(""))
        self.AG_tab2Diagram = QtGui.QWidget()
        self.AG_tab2Diagram.setObjectName(_fromUtf8("AG_tab2Diagram"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.AG_tab2Diagram)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.AG_tab2mpl = MplWidget(self.AG_tab2Diagram)
        self.AG_tab2mpl.setObjectName(_fromUtf8("AG_tab2mpl"))
#        self.AG_tab2mpl.setMinimumSize(QtCore.QSize(900, 420))
        self.verticalLayout_2.addWidget(self.AG_tab2mpl)
        self.tabWidget_Agilent.addTab(self.AG_tab2Diagram, _fromUtf8(""))
        self.AG_tab2Summary = QtGui.QWidget()
        self.AG_tab2Summary.setObjectName(_fromUtf8("AG_tab2Summary"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.AG_tab2Summary)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.AG_tab2SummaryTab = QtGui.QTableView(self.AG_tab2Summary)
        self.AG_tab2SummaryTab.setObjectName(_fromUtf8("AG_tab2SummaryTab"))
        self.verticalLayout_15.addWidget(self.AG_tab2SummaryTab)
        self.tabWidget_Agilent.addTab(self.AG_tab2Summary, _fromUtf8(""))
        self.verticalLayout_16.addWidget(self.tabWidget_Agilent)
        self.stackedWidget.addWidget(self.stacked_Agilent)
        self.stacked_Stromzaehler = QtGui.QWidget()
        self.stacked_Stromzaehler.setObjectName(_fromUtf8("stacked_Stromzähler"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.stacked_Stromzaehler)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.tabWidget_Strom = QtGui.QTabWidget(self.stacked_Stromzaehler)
        self.tabWidget_Strom.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Strom.sizePolicy().hasHeightForWidth())
        self.tabWidget_Strom.setSizePolicy(sizePolicy)
        self.tabWidget_Strom.setMinimumSize(QtCore.QSize(691, 400))
        self.tabWidget_Strom.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_Strom.setSizeIncrement(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget_Strom.setFont(font)
        self.tabWidget_Strom.setMouseTracking(False)
        self.tabWidget_Strom.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget_Strom.setAcceptDrops(False)
        self.tabWidget_Strom.setAutoFillBackground(False)
        self.tabWidget_Strom.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_Strom.setDocumentMode(True)
        self.tabWidget_Strom.setTabsClosable(False)
        self.tabWidget_Strom.setMovable(True)
        self.tabWidget_Strom.setObjectName(_fromUtf8("tabWidget_Strom"))
        self.Strom_tab2table = QtGui.QWidget()
        self.Strom_tab2table.setObjectName(_fromUtf8("Strom_tab2table"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.Strom_tab2table)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.Strom_tab2TableView = QtGui.QTableView(self.Strom_tab2table)
        self.Strom_tab2TableView.setMinimumSize(QtCore.QSize(631, 300))
        self.Strom_tab2TableView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Strom_tab2TableView.setAutoFillBackground(True)
        self.Strom_tab2TableView.setShowGrid(True)
        self.Strom_tab2TableView.setObjectName(_fromUtf8("Strom_tab2TableView"))
        self.verticalLayout_9.addWidget(self.Strom_tab2TableView)
        self.tabWidget_Strom.addTab(self.Strom_tab2table, _fromUtf8(""))
        self.Strom_tab2Calc = QtGui.QWidget()
        self.Strom_tab2Calc.setObjectName(_fromUtf8("Strom_tab2Calc"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.Strom_tab2Calc)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.Strom_tab2CalcTab = QtGui.QTableView(self.Strom_tab2Calc)
        self.Strom_tab2CalcTab.setObjectName(_fromUtf8("Strom_tab2CalcTab"))
        self.verticalLayout_7.addWidget(self.Strom_tab2CalcTab)
        self.tabWidget_Strom.addTab(self.Strom_tab2Calc, _fromUtf8(""))
        self.Strom_tab2Diagram = QtGui.QWidget()
        self.Strom_tab2Diagram.setObjectName(_fromUtf8("Strom_tab2Diagram"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.Strom_tab2Diagram)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.Strom_tab2mpl = MplWidget(self.Strom_tab2Diagram)
        self.Strom_tab2mpl.setObjectName(_fromUtf8("Strom_tab2mpl"))
        self.verticalLayout_10.addWidget(self.Strom_tab2mpl)
        self.tabWidget_Strom.addTab(self.Strom_tab2Diagram, _fromUtf8(""))
        self.Strom_tab2Summary = QtGui.QWidget()
        self.Strom_tab2Summary.setObjectName(_fromUtf8("Strom_tab2Summary"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.Strom_tab2Summary)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.Strom_tab2SummaryTab = QtGui.QTableView(self.Strom_tab2Summary)
        self.Strom_tab2SummaryTab.setObjectName(_fromUtf8("Strom_tab2SummaryTab"))
        self.verticalLayout_8.addWidget(self.Strom_tab2SummaryTab)
        self.tabWidget_Strom.addTab(self.Strom_tab2Summary, _fromUtf8(""))
        self.verticalLayout_11.addWidget(self.tabWidget_Strom)
        self.stackedWidget.addWidget(self.stacked_Stromzaehler)
        self.stacked_Wetterstation = QtGui.QWidget()
        self.stacked_Wetterstation.setObjectName(_fromUtf8("stacked_Wetterstation"))
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.stacked_Wetterstation)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.tabWidget_Wetter = QtGui.QTabWidget(self.stacked_Wetterstation)
        self.tabWidget_Wetter.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Wetter.sizePolicy().hasHeightForWidth())
        self.tabWidget_Wetter.setSizePolicy(sizePolicy)
        self.tabWidget_Wetter.setMinimumSize(QtCore.QSize(691, 400))
        self.tabWidget_Wetter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_Wetter.setSizeIncrement(QtCore.QSize(10, 10))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget_Wetter.setFont(font)
        self.tabWidget_Wetter.setMouseTracking(False)
        self.tabWidget_Wetter.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget_Wetter.setAcceptDrops(False)
        self.tabWidget_Wetter.setAutoFillBackground(False)
        self.tabWidget_Wetter.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget_Wetter.setDocumentMode(True)
        self.tabWidget_Wetter.setTabsClosable(False)
        self.tabWidget_Wetter.setMovable(True)
        self.tabWidget_Wetter.setObjectName(_fromUtf8("tabWidget_Wetter"))
        self.Wetter_tab2table = QtGui.QWidget()
        self.Wetter_tab2table.setObjectName(_fromUtf8("Wetter_tab2table"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.Wetter_tab2table)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.Wetter_tab2TableView = QtGui.QTableView(self.Wetter_tab2table)
        self.Wetter_tab2TableView.setMinimumSize(QtCore.QSize(631, 300))
        self.Wetter_tab2TableView.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Wetter_tab2TableView.setAutoFillBackground(True)
        self.Wetter_tab2TableView.setShowGrid(True)
        self.Wetter_tab2TableView.setObjectName(_fromUtf8("Wetter_tab2TableView"))
        self.verticalLayout_5.addWidget(self.Wetter_tab2TableView)
        self.tabWidget_Wetter.addTab(self.Wetter_tab2table, _fromUtf8(""))
        self.Wetter_tab2Calc = QtGui.QWidget()
        self.Wetter_tab2Calc.setObjectName(_fromUtf8("Wetter_tab2Calc"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.Wetter_tab2Calc)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.Wetter_tab2CalcTab = QtGui.QTableView(self.Wetter_tab2Calc)
        self.Wetter_tab2CalcTab.setObjectName(_fromUtf8("Wetter_tab2CalcTab"))
        self.verticalLayout_14.addWidget(self.Wetter_tab2CalcTab)
        self.tabWidget_Wetter.addTab(self.Wetter_tab2Calc, _fromUtf8(""))
        self.Wetter_tab2Diagram = QtGui.QWidget()
        self.Wetter_tab2Diagram.setObjectName(_fromUtf8("Wetter_tab2Diagram"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.Wetter_tab2Diagram)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.Wetter_tab2mpl = MplWidget(self.Wetter_tab2Diagram)
        self.Wetter_tab2mpl.setObjectName(_fromUtf8("Wetter_tab2mpl"))
        self.verticalLayout_6.addWidget(self.Wetter_tab2mpl)
        self.tabWidget_Wetter.addTab(self.Wetter_tab2Diagram, _fromUtf8(""))
        self.Wetter_tab2Summary = QtGui.QWidget()
        self.Wetter_tab2Summary.setObjectName(_fromUtf8("Wetter_tab2Summary"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.Wetter_tab2Summary)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.Wetter_tab2SummaryTab = QtGui.QTableView(self.Wetter_tab2Summary)
        self.Wetter_tab2SummaryTab.setObjectName(_fromUtf8("Wetter_tab2SummaryTab"))
        self.verticalLayout_12.addWidget(self.Wetter_tab2SummaryTab)
        self.tabWidget_Wetter.addTab(self.Wetter_tab2Summary, _fromUtf8(""))
        self.verticalLayout_17.addWidget(self.tabWidget_Wetter)
        self.stackedWidget.addWidget(self.stacked_Wetterstation)
        self.gridLayout_6.addWidget(self.stackedWidget, 2, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(720, 115))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 121))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1data = QtGui.QWidget()
        self.tab1data.setObjectName(_fromUtf8("tab1data"))
        self.tabWidget.addTab(self.tab1data, _fromUtf8(""))
        self.tab1val = QtGui.QWidget()
        self.tab1val.setObjectName(_fromUtf8("tab1val"))
        self.tabWidget.addTab(self.tab1val, _fromUtf8(""))
        self.tab1conv = QtGui.QWidget()
        self.tab1conv.setObjectName(_fromUtf8("tab1conv"))
        self.tabWidget.addTab(self.tab1conv, _fromUtf8(""))
        self.tab1Med = QtGui.QWidget()
        self.tab1Med.setObjectName(_fromUtf8("tab1Med"))
        self.tab1Med_label_HCir = QtGui.QLabel(self.tab1Med)
        self.tab1Med_label_HCir.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.tab1Med_label_HCir.setObjectName(_fromUtf8("tab1Med_label_HCir"))
        self.tab1Med_combo_HCir = QtGui.QComboBox(self.tab1Med)
        self.tab1Med_combo_HCir.setGeometry(QtCore.QRect(9, 30, 281, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab1Med_combo_HCir.sizePolicy().hasHeightForWidth())
        self.tab1Med_combo_HCir.setSizePolicy(sizePolicy)
        self.tab1Med_combo_HCir.setObjectName(_fromUtf8("tab1Med_combo_HCir"))
        self.tab1Med_combo_HCir.addItem(_fromUtf8(""))
        self.tab1Med_combo_HCir.addItem(_fromUtf8(""))
        self.tab1Med_combo_HCir.addItem(_fromUtf8(""))
        self.tab1Med_combo_HCir.addItem(_fromUtf8(""))
        self.tab1Med_combo_HCir.addItem(_fromUtf8(""))
        self.tab1Med_combo_HCir.addItem(_fromUtf8(""))
        self.tab1Med_combo_HCir.addItem(_fromUtf8(""))
        self.tab1Med_label_BCir = QtGui.QLabel(self.tab1Med)
        self.tab1Med_label_BCir.setGeometry(QtCore.QRect(350, 10, 171, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab1Med_label_BCir.sizePolicy().hasHeightForWidth())
        self.tab1Med_label_BCir.setSizePolicy(sizePolicy)
        self.tab1Med_label_BCir.setObjectName(_fromUtf8("tab1Med_label_BCir"))
        self.tab1Med_combo_BCir = QtGui.QComboBox(self.tab1Med)
        self.tab1Med_combo_BCir.setGeometry(QtCore.QRect(350, 30, 321, 20))
        self.tab1Med_combo_BCir.setObjectName(_fromUtf8("tab1Med_combo_BCir"))
        self.tab1Med_Btn_apply = QtGui.QPushButton(self.tab1Med)
        self.tab1Med_Btn_apply.setGeometry(QtCore.QRect(350, 60, 75, 21))
        self.tab1Med_Btn_apply.setObjectName(_fromUtf8("tab1Med_Btn_apply"))
        self.tab1Med_line_temp = QtGui.QLineEdit(self.tab1Med)
        self.tab1Med_line_temp.setGeometry(QtCore.QRect(440, 60, 113, 20))
        self.tab1Med_line_temp.setObjectName(_fromUtf8("tab1Med_line_temp"))
        self.tab1Med_line_P = QtGui.QLineEdit(self.tab1Med)
        self.tab1Med_line_P.setGeometry(QtCore.QRect(560, 60, 113, 20))
        self.tab1Med_line_P.setText(_fromUtf8(""))
        self.tab1Med_line_P.setObjectName(_fromUtf8("tab1Med_line_P"))
        self.tab1Med_label = QtGui.QLabel(self.tab1Med)
        self.tab1Med_label.setGeometry(QtCore.QRect(10, 60, 281, 21))
        self.tab1Med_label.setObjectName(_fromUtf8("tab1Med_label"))
        self.tabWidget.addTab(self.tab1Med, _fromUtf8(""))
        self.gridLayout_6.addWidget(self.tabWidget, 0, 1, 2, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.mainMenubar = QtGui.QMenuBar(MainWindow)
        self.mainMenubar.setGeometry(QtCore.QRect(0, 0, 1189, 23))
        self.mainMenubar.setObjectName(_fromUtf8("mainMenubar"))
        self.menuFile = QtGui.QMenu(self.mainMenubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.mainMenubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuView = QtGui.QMenu(self.mainMenubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.mainMenubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.mainMenubar)
        self.mainStatusbar = QtGui.QStatusBar(MainWindow)
        self.mainStatusbar.setObjectName(_fromUtf8("mainStatusbar"))
        MainWindow.setStatusBar(self.mainStatusbar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setObjectName(_fromUtf8("actionSave_as"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionPreference = QtGui.QAction(MainWindow)
        self.actionPreference.setObjectName(_fromUtf8("actionPreference"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionPreference)
        self.mainMenubar.addAction(self.menuFile.menuAction())
        self.mainMenubar.addAction(self.menuEdit.menuAction())
        self.mainMenubar.addAction(self.menuView.menuAction())
        self.mainMenubar.addAction(self.menuHelp.menuAction())
        self.mainToolBar.addAction(self.actionImport)
        self.mainToolBar.addAction(self.actionExport)

        self.retranslateUi(MainWindow)
        self.stackedWidget_List.setCurrentIndex(0)
        self.toolBox_AG.setCurrentIndex(0)
        self.toolBox_AG.layout().setSpacing(10)
        self.toolBox_Strom.setCurrentIndex(0)
        self.toolBox_Strom.layout().setSpacing(10)
        self.toolBox_Wetter.setCurrentIndex(0)
        self.toolBox_Wetter.layout().setSpacing(10)
        self.stackedWidget.setCurrentIndex(0)
        self.tabWidget_Agilent.setCurrentIndex(2)
        self.tabWidget_Strom.setCurrentIndex(2)
        self.tabWidget_Wetter.setCurrentIndex(2)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.boxTableBtnCalc_AG.setText(_translate("MainWindow", "Calculate", None))
        self.toolBox_AG.setItemText(self.toolBox_AG.indexOf(self.boxpageTable_AG), _translate("MainWindow", "Agilent", None))
        self.boxDiagramBtnPlot_AG.setText(_translate("MainWindow", "Plot", None))
        self.boxDiagramBtnNW_AG.setText(_translate("MainWindow", "New Window", None))
        self.toolBox_AG.setItemText(self.toolBox_AG.indexOf(self.boxpageDiagram_AG), _translate("MainWindow", "Diagram", None))
        self.boxTableBtnCalc_Strom.setText(_translate("MainWindow", "Calculate", None))
        self.toolBox_Strom.setItemText(self.toolBox_Strom.indexOf(self.boxpageTable_Strom), _translate("MainWindow", "Stromzähler", None))
        self.boxDiagramBtnPlot_Strom.setText(_translate("MainWindow", "Plot", None))
        self.boxDiagramBtnNW_Strom.setText(_translate("MainWindow", "New Window", None))
        self.toolBox_Strom.setItemText(self.toolBox_Strom.indexOf(self.boxpageDiagram_Strom), _translate("MainWindow", "Diagram", None))
        self.boxTableBtnCalc_Wetter.setText(_translate("MainWindow", "Calculate", None))
        self.toolBox_Wetter.setItemText(self.toolBox_Wetter.indexOf(self.boxpageTable_Wetter), _translate("MainWindow", "Wetterstation", None))
        self.boxDiagramBtnPlot_Wetter.setText(_translate("MainWindow", "Plot", None))
        self.boxDiagramBtnNW_Wetter.setText(_translate("MainWindow", "New Window", None))
        self.toolBox_Wetter.setItemText(self.toolBox_Wetter.indexOf(self.boxpageDiagram_Wetter), _translate("MainWindow", "Diagram", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "Agilent", None))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "Stromzähler", None))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "Wetterstation", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabWidget_Agilent.setTabText(self.tabWidget_Agilent.indexOf(self.AG_tab2table), _translate("MainWindow", "Agilent", None))
        self.tabWidget_Agilent.setTabText(self.tabWidget_Agilent.indexOf(self.AG_tab2Calc), _translate("MainWindow", "Calculation", None))
        self.tabWidget_Agilent.setTabText(self.tabWidget_Agilent.indexOf(self.AG_tab2Diagram), _translate("MainWindow", "Diagram", None))
        self.tabWidget_Agilent.setTabText(self.tabWidget_Agilent.indexOf(self.AG_tab2Summary), _translate("MainWindow", "Summary", None))
        self.tabWidget_Strom.setTabText(self.tabWidget_Strom.indexOf(self.Strom_tab2table), _translate("MainWindow", "Stromzähler", None))
        self.tabWidget_Strom.setTabText(self.tabWidget_Strom.indexOf(self.Strom_tab2Calc), _translate("MainWindow", "Calculation", None))
        self.tabWidget_Strom.setTabText(self.tabWidget_Strom.indexOf(self.Strom_tab2Diagram), _translate("MainWindow", "Diagram", None))
        self.tabWidget_Strom.setTabText(self.tabWidget_Strom.indexOf(self.Strom_tab2Summary), _translate("MainWindow", "Summary", None))
        self.tabWidget_Wetter.setTabText(self.tabWidget_Wetter.indexOf(self.Wetter_tab2table), _translate("MainWindow", "Wetterstation", None))
        self.tabWidget_Wetter.setTabText(self.tabWidget_Wetter.indexOf(self.Wetter_tab2Calc), _translate("MainWindow", "Calculation", None))
        self.tabWidget_Wetter.setTabText(self.tabWidget_Wetter.indexOf(self.Wetter_tab2Diagram), _translate("MainWindow", "Diagram", None))
        self.tabWidget_Wetter.setTabText(self.tabWidget_Wetter.indexOf(self.Wetter_tab2Summary), _translate("MainWindow", "Summary", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1data), _translate("MainWindow", "Data", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1val), _translate("MainWindow", "Values", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1conv), _translate("MainWindow", "Calculation", None))
        self.tab1Med_label_HCir.setText(_translate("MainWindow", "Heating Circut", None))
        self.tab1Med_combo_HCir.setItemText(0, _translate("MainWindow", "Glykosol N, Ethylene Glycol - 20%", None))
        self.tab1Med_combo_HCir.setItemText(1, _translate("MainWindow", "Glykosol N, Ethylene Glycol - 25%", None))
        self.tab1Med_combo_HCir.setItemText(2, _translate("MainWindow", "Glykosol N, Ethylene Glycol - 30%", None))
        self.tab1Med_combo_HCir.setItemText(3, _translate("MainWindow", "Glykosol N, Ethylene Glycol - 35%", None))
        self.tab1Med_combo_HCir.setItemText(4, _translate("MainWindow", "Glykosol N, Ethylene Glycol - 40%", None))
        self.tab1Med_combo_HCir.setItemText(5, _translate("MainWindow", "Glykosol N, Ethylene Glycol - 45%", None))
        self.tab1Med_combo_HCir.setItemText(6, _translate("MainWindow", "Glykosol N, Ethylene Glycol - 50%", None))
        self.tab1Med_label_BCir.setText(_translate("MainWindow", "Brine Circut", None))
        self.tab1Med_Btn_apply.setText(_translate("MainWindow", "Apply", None))
        self.tab1Med_line_temp.setPlaceholderText(_translate("MainWindow", "Temperature", None))
        self.tab1Med_line_P.setPlaceholderText(_translate("MainWindow", "Pressure", None))
        self.tab1Med_label.setText(_translate("MainWindow", "Medium", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1Med), _translate("MainWindow", "Medium", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.menuView.setTitle(_translate("MainWindow", "View", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.mainToolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_as.setText(_translate("MainWindow", "Save As...", None))
        self.actionClose.setText(_translate("MainWindow", "Exit", None))
        self.actionExport.setText(_translate("MainWindow", "Export", None))
        self.actionImport.setText(_translate("MainWindow", "Import", None))
        self.actionImport.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionPreference.setText(_translate("MainWindow", "Preference", None))


from mplwidget import *
if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

